"""
Data models for the retrieval pipeline
"""
from dataclasses import dataclass
from typing import List, Dict, Optional
import time


@dataclass
class QueryEmbedding:
    """
    Vector representation of a user query generated by the Cohere model
    """
    vector: List[float]
    query_text: str
    model_name: str = "multilingual-22-12-embed"

    def __post_init__(self):
        """Validate the query embedding"""
        if len(self.vector) != 768:
            raise ValueError(f"Vector must have 768 dimensions, got {len(self.vector)}")
        if not self.query_text.strip():
            raise ValueError("Query text must not be empty")
        if not all(isinstance(v, (int, float)) and not (v != v) for v in self.vector):  # Check for finite numbers
            raise ValueError("All vector values must be finite numbers")


@dataclass
class RetrievedChunk:
    """
    Content fragment returned from Qdrant that matches the query
    """
    id: str
    text: str
    url: str
    section: str
    chunk_index: int
    source: str
    similarity_score: float

    def __post_init__(self):
        """Validate the retrieved chunk"""
        if not self.text.strip():
            raise ValueError("Text must not be empty")
        if not 0 <= self.similarity_score <= 1:
            raise ValueError("Similarity score must be between 0 and 1")
        if self.chunk_index < 0:
            raise ValueError("Chunk index must be non-negative")


@dataclass
class RetrievalResult:
    """
    Collection of top-k relevant chunks with associated similarity scores and metadata
    """
    query: str
    query_embedding: QueryEmbedding
    chunks: List[RetrievedChunk]
    retrieval_time: float
    parameters: Dict[str, any]

    def __post_init__(self):
        """Validate the retrieval result"""
        if self.retrieval_time <= 0:
            raise ValueError("Retrieval time must be positive")
        if not self.query.strip():
            raise ValueError("Query must not be empty")


@dataclass
class ValidationMetrics:
    """
    Quality measures for retrieval performance
    """
    precision_score: float
    consistency_score: float
    retrieval_time_avg: float
    success_rate: float
    test_queries: List[str]

    def __post_init__(self):
        """Validate the validation metrics"""
        if not 0 <= self.precision_score <= 1:
            raise ValueError("Precision score must be between 0 and 1")
        if not 0 <= self.consistency_score <= 1:
            raise ValueError("Consistency score must be between 0 and 1")
        if not 0 <= self.success_rate <= 1:
            raise ValueError("Success rate must be between 0 and 1")
        if self.retrieval_time_avg < 0:
            raise ValueError("Average retrieval time must be non-negative")