"""
Web Content Ingestion and Vector Embedding Pipeline for RAG Chatbot

This script implements a complete pipeline to:
1. Crawl all URLs from a GitHub Pages Docusaurus site
2. Extract clean text content from each page
3. Chunk the text into semantic segments
4. Generate embeddings using Cohere
5. Store embeddings in Qdrant vector database
"""

import os
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from urllib.robotparser import RobotFileParser
import cohere
from qdrant_client import QdrantClient
from qdrant_client.http import models
from dotenv import load_dotenv
import time
import logging
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass
from typing import List, Dict, Optional

# Data Model Classes
@dataclass
class ContentChunk:
    """
    Represents a segment of extracted text from the book
    """
    id: str
    text: str
    url: str
    section: str = ""
    chunk_index: int = 0
    source: str = "web_content"

@dataclass
class VectorEmbedding:
    """
    Numeric representation of content semantics generated by the Cohere model
    """
    id: str
    vector: List[float]
    content_chunk_id: str

@dataclass
class ConfigurationParameters:
    """
    Settings that control the ingestion process
    """
    source_url: str
    chunk_size: int = 512
    chunk_overlap: int = 128
    cohere_model: str = "multilingual-22-12-embed"
    qdrant_collection: str = "rag_embedding"

    def validate(self) -> List[str]:
        """
        Validate configuration parameters and return list of validation errors
        """
        errors = []

        # Validate source URL format
        if not self.source_url or not self.source_url.startswith(('http://', 'https://')):
            errors.append("source_url must be a valid HTTP/HTTPS URL")

        # Validate chunk_size is positive
        if self.chunk_size <= 0:
            errors.append("chunk_size must be a positive integer")

        # Validate chunk_overlap is non-negative and smaller than chunk_size
        if self.chunk_overlap < 0:
            errors.append("chunk_overlap must be non-negative")
        if self.chunk_overlap >= self.chunk_size:
            errors.append("chunk_overlap must be smaller than chunk_size")

        # Validate cohere_model is not empty
        if not self.cohere_model.strip():
            errors.append("cohere_model cannot be empty")

        # Validate qdrant_collection is not empty
        if not self.qdrant_collection.strip():
            errors.append("qdrant_collection cannot be empty")

        return errors

    @classmethod
    def from_env(cls) -> 'ConfigurationParameters':
        """
        Create ConfigurationParameters from environment variables
        """
        source_url = os.getenv("SOURCE_URL", "https://maryamhussan.github.io/Physical-AI-And-Humanoid-Robotics")
        chunk_size = int(os.getenv("CHUNK_SIZE", "512"))
        chunk_overlap = int(os.getenv("CHUNK_OVERLAP", "128"))
        cohere_model = os.getenv("COHERE_MODEL", "multilingual-22-12-embed")
        qdrant_collection = os.getenv("QDRANT_COLLECTION", "rag_embedding")

        return cls(
            source_url=source_url,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            cohere_model=cohere_model,
            qdrant_collection=qdrant_collection
        )

    def to_dict(self) -> Dict[str, any]:
        """
        Convert configuration to dictionary
        """
        return {
            'source_url': self.source_url,
            'chunk_size': self.chunk_size,
            'chunk_overlap': self.chunk_overlap,
            'cohere_model': self.cohere_model,
            'qdrant_collection': self.qdrant_collection
        }

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Initialize Cohere client
cohere_api_key = os.getenv("COHERE_API_KEY")
if not cohere_api_key:
    raise ValueError("COHERE_API_KEY environment variable is required")
co = cohere.Client(cohere_api_key)

# Initialize Qdrant client
qdrant_url = os.getenv("QDRANT_URL")
qdrant_api_key = os.getenv("QDRANT_API_KEY")

if qdrant_url and qdrant_api_key:
    qdrant_client = QdrantClient(url=qdrant_url, api_key=qdrant_api_key)
elif qdrant_url:
    qdrant_client = QdrantClient(url=qdrant_url)
else:
    # Use local Qdrant instance if no URL provided
    qdrant_client = QdrantClient(host="localhost", port=6333)

def get_all_urls(base_url: str) -> List[str]:
    """
    Discover all accessible URLs from the GitHub Pages site

    Args:
        base_url: The base URL of the GitHub Pages site

    Returns:
        List of all discovered URLs
    """
    logger.info(f"Starting to crawl URLs from: {base_url}")

    # Check robots.txt
    robots_url = urljoin(base_url, "/robots.txt")
    try:
        rp = RobotFileParser()
        rp.set_url(robots_url)
        rp.read()
    except:
        logger.warning("Could not read robots.txt, proceeding anyway")

    all_urls = set()
    to_visit = [base_url]
    visited = set()

    # Common file extensions to avoid
    skip_extensions = {'.pdf', '.jpg', '.jpeg', '.png', '.gif', '.css', '.js', '.ico', '.svg'}

    while to_visit:
        current_url = to_visit.pop(0)

        if current_url in visited:
            continue

        visited.add(current_url)

        try:
            # Check if allowed by robots.txt
            if 'rp' in locals():
                if not rp.can_fetch("*", current_url):
                    logger.info(f"Robots.txt disallows: {current_url}")
                    continue

            response = requests.get(current_url, timeout=10)
            response.raise_for_status()

            # Check if content type is HTML
            content_type = response.headers.get('content-type', '').lower()
            if 'text/html' not in content_type:
                continue

            soup = BeautifulSoup(response.text, 'html.parser')
            all_urls.add(current_url)

            # Find all links on the page
            for link in soup.find_all('a', href=True):
                href = link['href']

                # Convert relative URLs to absolute
                absolute_url = urljoin(current_url, href)

                # Only process URLs from the same domain
                if urlparse(absolute_url).netloc == urlparse(base_url).netloc:
                    # Skip if it has an extension we want to avoid
                    if any(absolute_url.lower().endswith(ext) for ext in skip_extensions):
                        continue

                    # Skip if it's an anchor link
                    if absolute_url.startswith('#'):
                        continue

                    # Add to visit list if not already visited
                    if absolute_url not in visited and absolute_url not in to_visit:
                        to_visit.append(absolute_url)

        except requests.RequestException as e:
            logger.error(f"Error crawling {current_url}: {e}")
            continue
        except Exception as e:
            logger.error(f"Unexpected error crawling {current_url}: {e}")
            continue

    logger.info(f"Discovered {len(all_urls)} URLs")
    return list(all_urls)

def extract_text_from_url(url: str) -> str:
    """
    Extract clean text content from a single page

    Args:
        url: URL to extract text from

    Returns:
        Clean text content from the page
    """
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')

        # Remove script and style elements
        for script in soup(["script", "style", "nav", "header", "footer", "aside"]):
            script.decompose()

        # Get text content
        text = soup.get_text()

        # Clean up text: remove extra whitespace
        lines = (line.strip() for line in text.splitlines())
        chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
        text = ' '.join(chunk for chunk in chunks if chunk)

        logger.info(f"Extracted {len(text)} characters from {url}")
        return text

    except Exception as e:
        logger.error(f"Error extracting text from {url}: {e}")
        return ""

def chunk_text(text: str, chunk_size: int = 512, overlap: int = 128) -> List[str]:
    """
    Split content into semantically meaningful chunks

    Args:
        text: Text to chunk
        chunk_size: Size of each chunk in characters
        overlap: Overlap between chunks in characters

    Returns:
        List of text chunks
    """
    if len(text) <= chunk_size:
        return [text]

    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size

        # If we're near the end, include the rest
        if end > len(text):
            end = len(text)

        chunk = text[start:end]
        chunks.append(chunk)

        # Move start by chunk_size - overlap to create overlap
        start = end - overlap

        # Handle case where remaining text is smaller than overlap
        if start >= len(text):
            break

        # Memory optimization: Clear large intermediate variables periodically
        if len(chunks) % 100 == 0:
            import gc
            gc.collect()

    logger.info(f"Text chunked into {len(chunks)} chunks")
    return chunks

def embed(text_chunk: str) -> List[float]:
    """
    Generate embeddings using Cohere API

    Args:
        text_chunk: Text to generate embeddings for

    Returns:
        Embedding vector as a list of floats
    """
    try:
        response = co.embed(
            texts=[text_chunk],
            model="multilingual-22-12-embed",  # Using Cohere's multilingual embedding model
            input_type="search_document"
        )

        embedding = response.embeddings[0]
        logger.debug(f"Generated embedding with {len(embedding)} dimensions")
        return embedding

    except Exception as e:
        logger.error(f"Error generating embedding for chunk: {e}")
        raise

def create_collection(collection_name: str = "rag_embedding"):
    """
    Initialize Qdrant collection named 'rag_embedding'

    Args:
        collection_name: Name of the collection to create
    """
    try:
        # Check if collection already exists
        collections = qdrant_client.get_collections()
        collection_names = [col.name for col in collections.collections]

        if collection_name in collection_names:
            logger.info(f"Collection '{collection_name}' already exists, using existing collection")
            return

        # Create new collection with 768-dim vectors (for Cohere embeddings)
        qdrant_client.create_collection(
            collection_name=collection_name,
            vectors_config=models.VectorParams(size=768, distance=models.Distance.COSINE),
        )

        logger.info(f"Created collection '{collection_name}' with 768-dim vectors")

    except Exception as e:
        logger.error(f"Error creating collection '{collection_name}': {e}")
        raise

def save_chunk_to_qdrant(content_chunk: ContentChunk, embedding: VectorEmbedding, collection_name: str = "rag_embedding"):
    """
    Store vectors with metadata in Qdrant

    Args:
        content_chunk: ContentChunk object containing the text and metadata
        embedding: VectorEmbedding object containing the vector
        collection_name: Name of the collection to store in
    """
    try:
        # Prepare the point to be inserted
        point = models.PointStruct(
            id=content_chunk.id,
            vector=embedding.vector,
            payload={
                "text": content_chunk.text,
                "url": content_chunk.url,
                "section": content_chunk.section,
                "chunk_index": content_chunk.chunk_index,
                "source": content_chunk.source
            }
        )

        # Upsert the point to the collection
        qdrant_client.upsert(
            collection_name=collection_name,
            points=[point]
        )

        logger.info(f"Saved chunk to Qdrant with ID: {content_chunk.id}")

    except Exception as e:
        logger.error(f"Error saving chunk to Qdrant: {e}")
        raise

def search_similar_content(query_text: str, top_k: int = 5, collection_name: str = "rag_embedding") -> List[Dict]:
    """
    Implement similarity search functionality for content retrieval

    Args:
        query_text: The text to search for similar content
        top_k: Number of top results to return
        collection_name: Name of the collection to search in

    Returns:
        List of dictionaries containing the most similar content chunks with their metadata
    """
    try:
        # Generate embedding for the query text
        query_embedding = embed(query_text)

        # Perform the search in Qdrant
        search_results = qdrant_client.search(
            collection_name=collection_name,
            query_vector=query_embedding,
            limit=top_k,
            with_payload=True
        )

        # Format the results
        results = []
        for result in search_results:
            results.append({
                "id": result.id,
                "text": result.payload.get("text", ""),
                "url": result.payload.get("url", ""),
                "section": result.payload.get("section", ""),
                "chunk_index": result.payload.get("chunk_index", 0),
                "score": result.score,
                "source": result.payload.get("source", "web_content")
            })

        logger.info(f"Found {len(results)} similar content chunks for query")
        return results

    except Exception as e:
        logger.error(f"Error performing similarity search: {e}")
        raise


def validate_query_performance(query_text: str, expected_time: float = 2.0, collection_name: str = "rag_embedding") -> bool:
    """
    Add query performance validation (under 2 seconds for 90% of queries)

    Args:
        query_text: The text to search for performance validation
        expected_time: Expected maximum time in seconds
        collection_name: Name of the collection to search in

    Returns:
        Boolean indicating if query performed within expected time
    """
    import time

    start_time = time.time()
    try:
        search_similar_content(query_text, top_k=5, collection_name=collection_name)
        end_time = time.time()

        query_time = end_time - start_time
        logger.info(f"Query executed in {query_time:.2f} seconds (limit: {expected_time}s)")

        return query_time <= expected_time
    except Exception as e:
        logger.error(f"Error validating query performance: {e}")
        return False


def check_content_exists(url: str, chunk_index: int, collection_name: str = "rag_embedding") -> bool:
    """
    Check if content already exists in Qdrant to avoid duplicates
    """
    try:
        import hashlib
        chunk_id = hashlib.md5(f"{url}_{chunk_index}_".encode()).hexdigest()

        # Try to retrieve the point by ID
        records = qdrant_client.retrieve(
            collection_name=collection_name,
            ids=[chunk_id],
            with_payload=True,
            with_vectors=False
        )

        return len(records) > 0
    except Exception:
        # If there's an error (e.g., collection doesn't exist), assume content doesn't exist
        return False


def get_content_hash(text: str, url: str, chunk_index: int) -> str:
    """
    Generate a consistent hash for content to ensure reproducibility across runs
    """
    import hashlib
    content_to_hash = f"{text}_{url}_{chunk_index}".encode('utf-8')
    return hashlib.sha256(content_to_hash).hexdigest()


def get_qdrant_usage_stats(collection_name: str = "rag_embedding") -> Dict[str, any]:
    """
    Implement Qdrant Cloud free tier usage monitoring
    """
    try:
        # Get collection info
        collection_info = qdrant_client.get_collection(collection_name)

        # Get point count
        point_count = collection_info.points_count

        # Calculate estimated usage (free tier is typically 5GB storage)
        # This is a simplified estimate - in a real implementation,
        # we would calculate actual vector storage size
        estimated_size_mb = point_count * 0.003  # Rough estimate: 3KB per vector point

        usage_stats = {
            "point_count": point_count,
            "estimated_size_mb": round(estimated_size_mb, 2),
            "collection_name": collection_name
        }

        logger.info(f"Qdrant usage stats: {usage_stats}")
        return usage_stats

    except Exception as e:
        logger.error(f"Error getting Qdrant usage stats: {e}")
        return {"error": str(e)}


def ensure_pipeline_reproducibility(config: ConfigurationParameters) -> bool:
    """
    Implement pipeline reproducibility with consistent results across runs
    """
    try:
        # Create a test collection name for reproducibility check
        import uuid
        test_collection = f"reproducibility_test_{uuid.uuid4().hex[:8]}"

        # Create the test collection
        qdrant_client.create_collection(
            collection_name=test_collection,
            vectors_config=models.VectorParams(size=768, distance=models.Distance.COSINE),
        )

        # Test with sample content
        sample_text = "This is a test document to verify pipeline reproducibility."
        sample_url = "https://example.com/test"

        # Generate embedding for the sample text
        embedding = embed(sample_text)

        # Create consistent ID using content hash
        content_hash = get_content_hash(sample_text, sample_url, 0)

        # Create content chunk with the consistent ID
        content_chunk = ContentChunk(
            id=content_hash,
            text=sample_text,
            url=sample_url,
            chunk_index=0,
            source="reproducibility_test"
        )

        # Create vector embedding
        vector_embedding = VectorEmbedding(
            id=content_hash,
            vector=embedding,
            content_chunk_id=content_hash
        )

        # Save to Qdrant
        save_chunk_to_qdrant(content_chunk, vector_embedding, test_collection)

        # Retrieve the content to verify consistency
        retrieved = qdrant_client.retrieve(
            collection_name=test_collection,
            ids=[content_hash],
            with_payload=True,
            with_vectors=True
        )

        # Clean up test collection
        qdrant_client.delete_collection(test_collection)

        success = len(retrieved) > 0 and retrieved[0].id == content_hash
        logger.info(f"Pipeline reproducibility check: {'PASSED' if success else 'FAILED'}")

        return success

    except Exception as e:
        logger.error(f"Error in pipeline reproducibility check: {e}")
        return False


@dataclass
class PipelineMetrics:
    """
    Track pipeline execution metrics for monitoring
    """
    total_urls_discovered: int = 0
    total_urls_processed: int = 0
    total_chunks_processed: int = 0
    total_chunks_skipped: int = 0  # Due to duplicates
    total_errors: int = 0
    start_time: float = 0.0
    end_time: float = 0.0

    @property
    def processing_time(self) -> float:
        return self.end_time - self.start_time if self.end_time > 0 else 0.0

    @property
    def success_rate(self) -> float:
        total_attempts = self.total_chunks_processed + self.total_chunks_skipped
        return (self.total_chunks_processed / total_attempts * 100) if total_attempts > 0 else 0.0


def process_with_incremental_updates(config: ConfigurationParameters):
    """
    Process the pipeline with incremental updates to avoid duplicate entries
    """
    logger.info(f"Starting incremental pipeline with config: {config}")

    # Initialize metrics tracking
    metrics = PipelineMetrics()
    metrics.start_time = time.time()

    try:
        # Step 1: Get all URLs
        urls = get_all_urls(config.source_url)
        metrics.total_urls_discovered = len(urls)

        if not urls:
            logger.warning("No URLs found, exiting")
            return 0

        # Step 2: Create Qdrant collection
        create_collection(config.qdrant_collection)

        # Step 3: Process each URL
        processed_count = 0
        for i, url in enumerate(urls):
            logger.info(f"Processing URL {i+1}/{len(urls)}: {url}")
            metrics.total_urls_processed += 1

            # Extract text
            text = extract_text_from_url(url)
            if not text.strip():
                logger.warning(f"No text extracted from {url}, skipping")
                continue

            # Chunk text
            chunks = chunk_text(text, chunk_size=config.chunk_size, overlap=config.chunk_overlap)

            # Process each chunk
            for j, chunk_text_content in enumerate(chunks):
                if not chunk_text_content.strip():
                    continue

                # Check if this content already exists to avoid duplicates
                if check_content_exists(url, j, config.qdrant_collection):
                    logger.info(f"Content already exists for URL {url} chunk {j}, skipping")
                    metrics.total_chunks_skipped += 1
                    continue

                try:
                    # Generate embedding
                    embedding_vector = embed(chunk_text_content)

                    # Create unique ID for this chunk
                    import hashlib
                    chunk_id = hashlib.md5(f"{url}_{j}_{len(chunk_text_content)}".encode()).hexdigest()

                    # Create ContentChunk object
                    content_chunk = ContentChunk(
                        id=chunk_id,
                        text=chunk_text_content,
                        url=url,
                        chunk_index=j,
                        source="web_content"
                    )

                    # Create VectorEmbedding object
                    vector_embedding = VectorEmbedding(
                        id=chunk_id,
                        vector=embedding_vector,
                        content_chunk_id=chunk_id
                    )

                    # Save to Qdrant
                    save_chunk_to_qdrant(content_chunk, vector_embedding, config.qdrant_collection)

                    processed_count += 1
                    metrics.total_chunks_processed += 1

                    # Add a small delay to respect API limits
                    time.sleep(0.1)

                except Exception as e:
                    logger.error(f"Error processing chunk {j} from {url}: {e}")
                    metrics.total_errors += 1
                    continue

        metrics.end_time = time.time()

        # Log pipeline metrics
        logger.info(f"Pipeline completed successfully.")
        logger.info(f"Metrics: {processed_count} new chunks, {metrics.total_chunks_skipped} skipped, {metrics.total_errors} errors")
        logger.info(f"Processing time: {metrics.processing_time:.2f} seconds")
        logger.info(f"Success rate: {metrics.success_rate:.2f}%")

        return processed_count

    except Exception as e:
        metrics.end_time = time.time()
        logger.error(f"Pipeline failed: {e}")
        raise


def main():
    """
    Execute the complete pipeline
    """
    logger.info("Starting web content ingestion pipeline")

    # Create configuration from environment variables
    config = ConfigurationParameters.from_env()

    # Validate configuration
    validation_errors = config.validate()
    if validation_errors:
        logger.error(f"Configuration validation failed: {validation_errors}")
        for error in validation_errors:
            logger.error(f"  - {error}")
        return

    logger.info(f"Using configuration: {config.to_dict()}")

    try:
        # Process with incremental updates to avoid duplicate entries
        processed_count = process_with_incremental_updates(config)

        # Demonstrate search functionality
        logger.info("Testing search functionality with sample query...")
        sample_query = "What is Physical AI and Humanoid Robotics?"
        search_results = search_similar_content(sample_query)

        if search_results:
            logger.info(f"Found {len(search_results)} relevant results:")
            for i, result in enumerate(search_results[:3]):  # Show first 3 results
                logger.info(f"Result {i+1}: Score {result['score']:.3f} from {result['url']}")
                logger.info(f"  Text preview: {result['text'][:100]}...")
        else:
            logger.info("No results found for the sample query")

        # Monitor Qdrant usage
        logger.info("Checking Qdrant usage statistics...")
        usage_stats = get_qdrant_usage_stats(config.qdrant_collection)
        logger.info(f"Qdrant usage: {usage_stats}")

    except Exception as e:
        logger.error(f"Pipeline failed: {e}")
        raise

def demonstrate_retrieval_functionality():
    """
    Enhance main.py to demonstrate retrieval functionality
    """
    from .retrieval.retriever import Retriever
    from .retrieval.validator import Validator

    logger.info("Demonstrating retrieval functionality...")

    # Create a retriever instance
    retriever = Retriever()

    # Sample queries to test the retrieval
    sample_queries = [
        "What is Physical AI and Humanoid Robotics?",
        "Explain machine learning applications in robotics",
        "What are the main components of a humanoid robot?"
    ]

    for query in sample_queries:
        logger.info(f"Processing query: {query}")
        try:
            result = retriever.retrieve(query)

            logger.info(f"Retrieved {len(result.chunks)} chunks for query: '{query[:50]}...'")
            for i, chunk in enumerate(result.chunks[:3]):  # Show first 3 results
                logger.info(f"  Result {i+1}: Score {chunk.similarity_score:.3f} from {chunk.url}")
                logger.info(f"    Text preview: {chunk.text[:100]}...")

        except Exception as e:
            logger.error(f"Error retrieving results for query '{query}': {e}")

    # Demonstrate validation capabilities
    logger.info("Running validation on retrieval system...")
    validator = Validator(retriever)

    try:
        validation_metrics = validator.validate_retrieval()
        logger.info(f"Validation Results:")
        logger.info(f"  Precision Score: {validation_metrics.precision_score:.3f}")
        logger.info(f"  Consistency Score: {validation_metrics.consistency_score:.3f}")
        logger.info(f"  Success Rate: {validation_metrics.success_rate:.3f}")
        logger.info(f"  Avg. Retrieval Time: {validation_metrics.retrieval_time_avg:.3f}s")
    except Exception as e:
        logger.error(f"Error during validation: {e}")


def demonstrate_agent_functionality():
    """
    Enhance main.py to demonstrate agent functionality
    """
    try:
        # Import the RAG agent
        from .agent.agent import RAGAgent
        from .agent.models import AgentRequest
        from datetime import datetime
        import uuid

        logger.info("Demonstrating RAG agent functionality...")

        # Create an agent instance
        agent = RAGAgent()

        # Sample queries to test the agent
        sample_queries = [
            "What is Physical AI and Humanoid Robotics?",
            "Explain machine learning applications in robotics",
            "What are the main components of a humanoid robot?"
        ]

        for query in sample_queries:
            logger.info(f"Processing agent query: {query}")
            try:
                # Create an agent request
                request = AgentRequest(
                    query=query,
                    request_id=str(uuid.uuid4()),
                    timestamp=datetime.now()
                )

                # Process the query with the agent
                result = agent.process_query(request)

                logger.info(f"Agent response: '{result.response[:100]}...'")
                logger.info(f"Sources used: {len(result.sources)}")
                logger.info(f"Confidence score: {result.confidence:.3f}")
                logger.info(f"Processing time: {result.processing_time:.3f}s")

            except Exception as e:
                logger.error(f"Error processing agent query '{query}': {e}")

        # Test with selected text context
        logger.info("Testing agent with selected text context...")
        request_with_context = AgentRequest(
            query="How does this relate to the provided context?",
            selected_text="Physical AI represents a paradigm shift in artificial intelligence where systems are designed to interact with the physical world in a more integrated and embodied way.",
            request_id=str(uuid.uuid4()),
            timestamp=datetime.now()
        )

        result = agent.process_query(request_with_context)
        logger.info(f"Agent response with context: '{result.response[:100]}...'")  # Fixed f-string syntax

    except ImportError as e:
        logger.warning(f"Agent module not available, skipping agent demonstration: {e}")
    except Exception as e:
        logger.error(f"Error demonstrating agent functionality: {e}")


def main():
    """
    Execute the complete pipeline
    """
    logger.info("Starting web content ingestion pipeline")

    # Target URL
    base_url = "https://maryamhussan.github.io/Physical-AI-And-Humanoid-Robotics"

    try:
        # Step 1: Get all URLs
        urls = get_all_urls(base_url)

        if not urls:
            logger.warning("No URLs found, exiting")
            return

        # Step 2: Create Qdrant collection
        create_collection("rag_embedding")

        # Step 3: Process each URL
        processed_count = 0
        for i, url in enumerate(urls):
            logger.info(f"Processing URL {i+1}/{len(urls)}: {url}")

            # Extract text
            text = extract_text_from_url(url)
            if not text.strip():
                logger.warning(f"No text extracted from {url}, skipping")
                continue

            # Chunk text
            chunks = chunk_text(text)

            # Process each chunk
            for j, chunk_text_content in enumerate(chunks):
                if not chunk_text_content.strip():
                    continue

                # Check if this content already exists to avoid duplicates
                if check_content_exists(url, j, "rag_embedding"):
                    logger.info(f"Content already exists for URL {url} chunk {j}, skipping")
                    continue

                try:
                    # Generate embedding
                    embedding_vector = embed(chunk_text_content)

                    # Create unique ID for this chunk
                    import hashlib
                    chunk_id = hashlib.md5(f"{url}_{j}_{len(chunk_text_content)}".encode()).hexdigest()

                    # Create ContentChunk object
                    content_chunk = ContentChunk(
                        id=chunk_id,
                        text=chunk_text_content,
                        url=url,
                        chunk_index=j,
                        source="web_content"
                    )

                    # Create VectorEmbedding object
                    vector_embedding = VectorEmbedding(
                        id=chunk_id,
                        vector=embedding_vector,
                        content_chunk_id=chunk_id
                    )

                    # Save to Qdrant
                    save_chunk_to_qdrant(content_chunk, vector_embedding, "rag_embedding")

                    processed_count += 1

                    # Add a small delay to respect API limits
                    time.sleep(0.1)

                    # Memory optimization: Clean up large variables and run garbage collection periodically
                    if j % 50 == 0:  # Every 50 chunks
                        del embedding_vector, content_chunk, vector_embedding  # Explicitly delete large objects
                        import gc
                        gc.collect()

                except Exception as e:
                    logger.error(f"Error processing chunk {j} from {url}: {e}")
                    continue

        logger.info(f"Pipeline completed successfully. Processed {processed_count} new content chunks.")

        # Demonstrate search functionality
        logger.info("Testing search functionality with sample query...")
        sample_query = "What is Physical AI and Humanoid Robotics?"
        search_results = search_similar_content(sample_query)

        if search_results:
            logger.info(f"Found {len(search_results)} relevant results:")
            for i, result in enumerate(search_results[:3]):  # Show first 3 results
                logger.info(f"Result {i+1}: Score {result['score']:.3f} from {result['url']}")
                logger.info(f"  Text preview: {result['text'][:100]}...")
        else:
            logger.info("No results found for the sample query")

        # Demonstrate retrieval functionality for RAG
        logger.info("Demonstrating RAG retrieval functionality...")
        demonstrate_retrieval_functionality()

        # Demonstrate agent functionality
        logger.info("Demonstrating RAG agent functionality...")
        demonstrate_agent_functionality()

    except Exception as e:
        logger.error(f"Pipeline failed: {e}")
        raise


if __name__ == "__main__":
    main()
